### ISSUE TITLE
Conversion between Petri Net and math equations

### ISSUE THREAD

**Issue by mwdchang** [DARPA-ASKEM/.github-private#15]
We should have the capability to

- [x] Convert a Petri net (acset representation) to a set of ODE equation representations
- [x] Convert a set of ODE equations into a Petri net
- [ ] Check with TA2 (UFlorida) if they have they already have the capabilities to do this - it seems like in the Semagram demo it can at least change Petri net to MathML??

If this is not possible we will need to investigate building the converters ourselves. Possible references:

http://susan-stepney.blogspot.com/2012/12/ode-to-petri-net.html
https://www.nature.com/articles/s41598-022-04849-0

**Comment by YohannParis** [comment]
https://docs.google.com/document/d/1chiRJIrFodz8-GjOaGhtaqiHt8c2sMuEJgKLQxDatUo/edit

**Comment by liunelson** [comment]
Notebook testing/demonstrating these conversions:
- [ ]  Petri net (ACSet JSON) to equations (LaTeX): https://github.com/DARPA-ASKEM/experiments/blob/main/notebooks/Nelson/model-repr-conversion/petri-to-equations.ipynb
- [ ] equations (LaTeX and MathML) to Petri net (ACSet JSON): https://github.com/DARPA-ASKEM/experiments/blob/main/python_sandbox/notebooks/model_petri_equation_conversion.py

**Comment by liunelson** [comment]
There are still various (minor) issues when it comes to the stability of the conversion between these two representations. See `Integration` discussion with JuliaHub (Chris R. and Yingbo) and UArizona (Adarsh).
- [ ] ModelingToolKit should not simplify equations since that would destroy Petri net structure needed for stratification
- [ ] SKEMA should handle unicode better when receiving MathML code (e.g. Greek letters, +, -, =, ...)
